// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Entry
	AppendEntries
	RequestVote
	Response
*/
package model

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntryType int32

const (
	EntryType_Nop  EntryType = 0
	EntryType_Data EntryType = 1
)

var EntryType_name = map[int32]string{
	0: "Nop",
	1: "Data",
}
var EntryType_value = map[string]int32{
	"Nop":  0,
	"Data": 1,
}

func (x EntryType) String() string {
	return proto.EnumName(EntryType_name, int32(x))
}
func (EntryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StateRole int32

const (
	StateRole_None      StateRole = 0
	StateRole_Dummy     StateRole = 1
	StateRole_Follower  StateRole = 2
	StateRole_Candidate StateRole = 3
	StateRole_Leader    StateRole = 4
)

var StateRole_name = map[int32]string{
	0: "None",
	1: "Dummy",
	2: "Follower",
	3: "Candidate",
	4: "Leader",
}
var StateRole_value = map[string]int32{
	"None":      0,
	"Dummy":     1,
	"Follower":  2,
	"Candidate": 3,
	"Leader":    4,
}

func (x StateRole) String() string {
	return proto.EnumName(StateRole_name, int32(x))
}
func (StateRole) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Entry struct {
	Version int32     `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Id      int64     `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Term    int64     `protobuf:"varint,3,opt,name=term" json:"term,omitempty"`
	Type    EntryType `protobuf:"varint,4,opt,name=type,enum=model.EntryType" json:"type,omitempty"`
	Payload []byte    `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Entry) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetType() EntryType {
	if m != nil {
		return m.Type
	}
	return EntryType_Nop
}

func (m *Entry) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type AppendEntries struct {
	Term         int64    `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	PrevLogIndex int64    `protobuf:"varint,2,opt,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	PrevLogTerm  int64    `protobuf:"varint,3,opt,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	LeaderCommit int64    `protobuf:"varint,4,opt,name=leaderCommit" json:"leaderCommit,omitempty"`
	LeaderID     string   `protobuf:"bytes,5,opt,name=leaderID" json:"leaderID,omitempty"`
	Entries      []*Entry `protobuf:"bytes,6,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *AppendEntries) Reset()                    { *m = AppendEntries{} }
func (m *AppendEntries) String() string            { return proto.CompactTextString(m) }
func (*AppendEntries) ProtoMessage()               {}
func (*AppendEntries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppendEntries) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntries) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntries) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntries) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

func (m *AppendEntries) GetLeaderID() string {
	if m != nil {
		return m.LeaderID
	}
	return ""
}

func (m *AppendEntries) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type RequestVote struct {
	Term         int64  `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LastLogIndex int64  `protobuf:"varint,2,opt,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	LastLogTerm  int64  `protobuf:"varint,3,opt,name=lastLogTerm" json:"lastLogTerm,omitempty"`
	CandidateID  string `protobuf:"bytes,4,opt,name=candidateID" json:"candidateID,omitempty"`
}

func (m *RequestVote) Reset()                    { *m = RequestVote{} }
func (m *RequestVote) String() string            { return proto.CompactTextString(m) }
func (*RequestVote) ProtoMessage()               {}
func (*RequestVote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestVote) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVote) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVote) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *RequestVote) GetCandidateID() string {
	if m != nil {
		return m.CandidateID
	}
	return ""
}

type Response struct {
	Term    int64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Entry)(nil), "model.Entry")
	proto.RegisterType((*AppendEntries)(nil), "model.AppendEntries")
	proto.RegisterType((*RequestVote)(nil), "model.RequestVote")
	proto.RegisterType((*Response)(nil), "model.Response")
	proto.RegisterEnum("model.EntryType", EntryType_name, EntryType_value)
	proto.RegisterEnum("model.StateRole", StateRole_name, StateRole_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x8e, 0x95, 0x30,
	0x14, 0x86, 0xa7, 0x17, 0xb8, 0xc0, 0x81, 0x99, 0x34, 0x5d, 0x35, 0x2e, 0x0c, 0x21, 0xc6, 0x90,
	0x59, 0xdc, 0xc5, 0xb8, 0x71, 0x6b, 0x06, 0x4d, 0x48, 0x26, 0xb3, 0xa8, 0x13, 0xf7, 0xf5, 0xf6,
	0xc4, 0x90, 0x00, 0xad, 0xb4, 0x77, 0x94, 0x07, 0x70, 0xe1, 0xe3, 0xf9, 0x46, 0x86, 0x0a, 0x57,
	0xc6, 0x38, 0x3b, 0xfe, 0xaf, 0x70, 0xce, 0xf7, 0x03, 0x90, 0xb9, 0xc9, 0xa0, 0x3d, 0x98, 0x51,
	0x3b, 0xcd, 0xa2, 0x5e, 0x2b, 0xec, 0xca, 0x1f, 0x04, 0xa2, 0xf7, 0x83, 0x1b, 0x27, 0xc6, 0x21,
	0x7e, 0xc4, 0xd1, 0xb6, 0x7a, 0xe0, 0xa4, 0x20, 0x55, 0x24, 0xd6, 0xc8, 0xae, 0x60, 0xd7, 0x2a,
	0xbe, 0x2b, 0x48, 0x15, 0x88, 0x5d, 0xab, 0x18, 0x83, 0xd0, 0xe1, 0xd8, 0xf3, 0xc0, 0x13, 0x7f,
	0xcd, 0x5e, 0x41, 0x38, 0x4f, 0xe7, 0x61, 0x41, 0xaa, 0xab, 0x1b, 0x7a, 0xf0, 0xd3, 0x0f, 0x7e,
	0xf2, 0xc3, 0x64, 0x50, 0xf8, 0xd3, 0x79, 0x87, 0x91, 0x53, 0xa7, 0xa5, 0xe2, 0x51, 0x41, 0xaa,
	0x5c, 0xac, 0xb1, 0xfc, 0x45, 0xe0, 0xf2, 0x9d, 0x31, 0x38, 0xa8, 0xf9, 0x99, 0x16, 0xed, 0x79,
	0x0b, 0xd9, 0x6c, 0x29, 0x21, 0x37, 0x23, 0x3e, 0xde, 0xe9, 0x2f, 0xcd, 0xa0, 0xf0, 0xfb, 0xe2,
	0xf4, 0x84, 0xb1, 0x02, 0xb2, 0x25, 0x3f, 0xfc, 0x95, 0xdc, 0xa2, 0x79, 0x4a, 0x87, 0x52, 0xe1,
	0x78, 0xab, 0xfb, 0xbe, 0x75, 0xde, 0x39, 0x10, 0x4f, 0x18, 0x7b, 0x01, 0xc9, 0x9f, 0xdc, 0xd4,
	0x5e, 0x35, 0x15, 0xe7, 0xcc, 0x5e, 0x43, 0xbc, 0x48, 0xf2, 0x7d, 0x11, 0x54, 0xd9, 0x4d, 0xbe,
	0xad, 0x2b, 0xd6, 0xc3, 0xf2, 0x27, 0x81, 0x4c, 0xe0, 0xd7, 0x13, 0x5a, 0xf7, 0x49, 0x3b, 0x7c,
	0xae, 0x51, 0x27, 0xad, 0xfb, 0xb7, 0xd1, 0x96, 0xcd, 0x8d, 0x96, 0xbc, 0x6d, 0xb4, 0x41, 0xf3,
	0x1d, 0x47, 0x39, 0xa8, 0x56, 0x49, 0x87, 0x4d, 0xed, 0x0b, 0xa5, 0x62, 0x8b, 0xca, 0xb7, 0x90,
	0x08, 0xb4, 0x46, 0x0f, 0xf6, 0xff, 0x1e, 0x1c, 0x62, 0x7b, 0x3a, 0x1e, 0xd1, 0x5a, 0xaf, 0x90,
	0x88, 0x35, 0x5e, 0xbf, 0x84, 0xf4, 0xfc, 0x19, 0x59, 0x0c, 0xc1, 0xbd, 0x36, 0xf4, 0x82, 0x25,
	0x10, 0xd6, 0xd2, 0x49, 0x4a, 0xae, 0x1b, 0x48, 0x3f, 0x3a, 0xe9, 0x50, 0xe8, 0x0e, 0x67, 0x7c,
	0xaf, 0x07, 0xa4, 0x17, 0x2c, 0x85, 0xa8, 0x3e, 0xf5, 0xfd, 0x44, 0x09, 0xcb, 0x21, 0xf9, 0xa0,
	0xbb, 0x4e, 0x7f, 0xc3, 0x91, 0xee, 0xd8, 0x25, 0xa4, 0xb7, 0xab, 0x18, 0x0d, 0x18, 0xc0, 0xfe,
	0xce, 0xbf, 0x58, 0x1a, 0x7e, 0xde, 0xfb, 0x5f, 0xf3, 0xcd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x32, 0xbc, 0xbd, 0x2d, 0xa9, 0x02, 0x00, 0x00,
}
